# Render Blueprint - AreaMédica API (FREE TIER - Testing)
# Documentation: https://render.com/docs/blueprint-spec
# Version: 1.0.0

services:
  # FastAPI Application
  - type: web
    name: areamedica-api
    runtime: docker
    plan: free  # ✅ FREE plan for testing (no credit card required)
    region: oregon
    dockerfilePath: ./docker/Dockerfile
    dockerContext: .

    # Auto-deploy configuration
    branch: main
    autoDeploy: true

    # Health check configuration
    healthCheckPath: /health

    # Environment variables
    envVars:
      # Application
      - key: ENVIRONMENT
        value: development  # ✅ Development mode for testing

      - key: DEBUG
        value: "true"  # ✅ Debug enabled for testing

      - key: LOG_LEVEL
        value: INFO

      # Security
      - key: SECRET_KEY
        value: test-secret-key-change-in-production-min-32-chars-abc123

      - key: ALGORITHM
        value: HS256

      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30

      # Database - Connect to Render PostgreSQL
      - key: DATABASE_URL
        fromDatabase:
          name: areamedica-db
          property: connectionString

      # CORS Configuration (allow all for testing)
      - key: CORS_ORIGINS
        value: "*"

      # Banesco Integration - Fake values for testing
      - key: BANESCO_BASE_URL
        value: https://fake-api.com

      - key: BANESCO_API_KEY
        value: test-api-key

      - key: BANESCO_USERNAME
        value: test-user

      - key: BANESCO_PASSWORD
        value: test-password

      - key: BANESCO_TIMEOUT
        value: 30

    # Build configuration
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements/prod.txt

    # Pre-deploy command (migrations)
    preDeployCommand: alembic upgrade head

# Databases
databases:
  # PostgreSQL Database
  - name: areamedica-db
    plan: free  # ✅ FREE plan (90 days free trial, then expires or upgrade)
    databaseName: areamedica
    user: areamedica_user
    region: oregon

    # Automatic backups
    ipAllowList: [] # Empty = accessible from all Render services

# ✅ REDIS REMOVED - Free plan doesn't support managed Redis
# The app will work without Redis for testing purposes

# Background Workers (optional)
# Uncomment if you need background job processing
# - type: worker
#   name: areamedica-worker
#   runtime: docker
#   plan: standard
#   region: oregon
#   dockerfilePath: ./docker/Dockerfile
#   dockerContext: .
#   branch: main
#   autoDeploy: true
#
#   # Worker command
#   startCommand: celery -A src.infrastructure.celery.app worker --loglevel=info
#
#   # Share environment variables with web service
#   envVars:
#     - fromGroup: areamedica-api

# Cron Jobs (optional)
# Uncomment for scheduled tasks
# - type: cron
#   name: areamedica-cleanup
#   runtime: docker
#   schedule: "0 2 * * *"  # Daily at 2 AM
#   dockerfilePath: ./docker/Dockerfile
#   dockerContext: .
#
#   # Cleanup command
#   startCommand: python -m src.scripts.cleanup_old_transactions
#
#   envVars:
#     - fromGroup: areamedica-api
