#cloud-config
# AreaMédica API - Monitoring Server Cloud Init
# Installs and configures Prometheus and Grafana

package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - apt-transport-https
  - software-properties-common
  - ufw

write_files:
  - path: /etc/prometheus/prometheus.yml
    content: |
      global:
        scrape_interval: 15s
        evaluation_interval: 15s

      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
        
        - job_name: 'node_exporter'
          static_configs:
            - targets: ['localhost:9100']
        
        - job_name: 'areamedica_api'
          static_configs:
            - targets: []  # Will be populated by Terraform
          metrics_path: '/metrics'
    permissions: "0644"
    owner: root:root

  - path: /etc/grafana/provisioning/datasources/prometheus.yml
    content: |
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://localhost:9090
          isDefault: true
          editable: true
    permissions: "0644"
    owner: root:root

runcmd:
  # Configure firewall
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22/tcp
  - ufw allow 9090/tcp # Prometheus
  - ufw allow 3000/tcp # Grafana
  - ufw --force enable

  # Install Prometheus
  - wget https://github.com/prometheus/prometheus/releases/download/v2.47.0/prometheus-2.47.0.linux-amd64.tar.gz
  - tar xvfz prometheus-2.47.0.linux-amd64.tar.gz
  - cp prometheus-2.47.0.linux-amd64/prometheus /usr/local/bin/
  - cp prometheus-2.47.0.linux-amd64/promtool /usr/local/bin/
  - mkdir -p /var/lib/prometheus
  - useradd -rs /bin/false prometheus
  - chown -R prometheus:prometheus /var/lib/prometheus
  - chown -R prometheus:prometheus /etc/prometheus

  # Create Prometheus systemd service
  - |
    cat > /etc/systemd/system/prometheus.service <<EOF
    [Unit]
    Description=Prometheus
    Wants=network-online.target
    After=network-online.target

    [Service]
    User=prometheus
    Group=prometheus
    Type=simple
    ExecStart=/usr/local/bin/prometheus \
      --config.file=/etc/prometheus/prometheus.yml \
      --storage.tsdb.path=/var/lib/prometheus/ \
      --web.console.templates=/etc/prometheus/consoles \
      --web.console.libraries=/etc/prometheus/console_libraries

    [Install]
    WantedBy=multi-user.target
    EOF

  # Start Prometheus
  - systemctl daemon-reload
  - systemctl start prometheus
  - systemctl enable prometheus

  # Install Node Exporter
  - wget https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz
  - tar xvfz node_exporter-1.6.1.linux-amd64.tar.gz
  - cp node_exporter-1.6.1.linux-amd64/node_exporter /usr/local/bin/
  - useradd -rs /bin/false node_exporter

  # Create Node Exporter systemd service
  - |
    cat > /etc/systemd/system/node_exporter.service <<EOF
    [Unit]
    Description=Node Exporter
    After=network.target

    [Service]
    User=node_exporter
    Group=node_exporter
    Type=simple
    ExecStart=/usr/local/bin/node_exporter

    [Install]
    WantedBy=multi-user.target
    EOF

  # Start Node Exporter
  - systemctl daemon-reload
  - systemctl start node_exporter
  - systemctl enable node_exporter

  # Install Grafana
  - wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
  - add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
  - apt-get update
  - apt-get install -y grafana

  # Create Grafana provisioning directories
  - mkdir -p /etc/grafana/provisioning/datasources
  - mkdir -p /etc/grafana/provisioning/dashboards

  # Start Grafana
  - systemctl start grafana-server
  - systemctl enable grafana-server

  # Install Docker for running additional monitoring tools
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker

final_message: "Monitoring server (Prometheus + Grafana) initialized successfully after $UPTIME seconds. Access Grafana at http://SERVER_IP:3000 (admin/admin)"
